name: Makefile CI

on:
  push:
    branches: [ testing/github_action ]
  pull_request:
    branches: [ testing/github_action ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.14'

    - name: Make all
      run: make
